apiVersion: apps/v1
kind: Deployment
metadata:
  name: Board
  labels:
    app: Board
spec:
  replicas: 1
  selector:
    matchLabels:
      app: Board
  template:
    metadata:
      labels:
        app: Board
    spec:
      containers:
        - name: Board
          image: 271153858532.dkr.ecr.ap-northeast-2.amazonaws.com/admin12-board:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5
